name: "Foo"

defaults:
  run:
    working-directory: "services/foo"

on:
  workflow_dispatch: ~
  pull_request:
    paths:
      - ".github/workflows/services.foo.yaml"
      - "services/foo/**"
  push:
    paths:
      - ".github/workflows/services.foo.yaml"
      - "services/foo/**"
    branches:
      - "main"

jobs:
  test:
    name: "Foo Test"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Test"
        run: |
          sleep 30
          if [ $(cat data | grep -c PASS) -eq 0 ]; then
            echo "FAIL"
            exit 1
          else
            echo "PASS"
            exit 0
          fi

  sanity-checker:
    name: "Sanity Checker"
    runs-on: "ubuntu-latest"
    needs: "test"
    if: ${{ failure() || cancelled() }}
    steps:
      - name: "Fail"
        run: exit 1
        working-directory: ./